import Link from "next/link";

export const metadata = { title: "Terms of Service — Tarana.ai" };

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-xl font-semibold text-gray-900">{heading}</h2>
      <div className="mt-3 space-y-3 text-sm leading-6 text-gray-600">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <div className="h-1 w-8 rounded-full bg-blue-600" />
        <h1 className="mt-4 text-3xl font-semibold tracking-tight text-gray-900">
          Terms of Service <span className="text-blue-600">— Tarana.ai</span>
        </h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: September 2026</p>

        <p className="mt-6 text-sm leading-6 text-gray-600">
          These terms govern your use of Tarana.ai. By creating an account or using the service,
          you agree to them. If you do not agree, please do not use Tarana.ai.
        </p>

        <Section heading="Service description">
          <p>
            Tarana.ai is an AI-powered Baguio travel companion. It generates personalized
            itineraries, meal ideas, routes, traffic insights, and weather context based on the
            preferences you enter. Plans are suggestions to help you explore — always confirm
            details locally before you travel.
          </p>
        </Section>

        <Section heading="Accounts">
          <p>
            You may register with an email and password or use Google sign-in. You are
            responsible for keeping your credentials confidential and for all activity under your
            account. Provide accurate information, and notify us promptly of any unauthorized use.
            You must be at least 13 years old to use the service.
          </p>
        </Section>

        <Section heading="Credits and referrals">
          <p>
            Certain generations consume credits. Accounts receive daily credits, and you can earn
            extra credits by inviting friends with your referral (invite) code. Credits have no cash
            value, are non-transferable except through the built-in referral flow, and may not be
            sold or exchanged. We may adjust credit allowances, referral rewards, or abuse-related
            forfeitures to protect the service, and we may reset balances tied to fraud or misuse.
          </p>
        </Section>

        <Section heading="Acceptable use">
          <ul className="list-disc space-y-1 pl-5">
            <li>Do not abuse, disrupt, overload, or attempt to breach the service.</li>
            <li>Do not create fake accounts, farm referrals, or manipulate credits.</li>
            <li>Do not submit unlawful, harmful, or infringing content.</li>
            <li>Do not scrape, reverse-engineer, or resell the service without permission.</li>
          </ul>
        </Section>

        <Section heading="AI, traffic, and weather accuracy disclaimer">
          <p>
            Itineraries are generated by our AI itinerary provider and routes, congestion
            estimates, and forecasts come from our mapping and traffic data provider and weather
            data provider. They are estimates for
            planning purposes only and may be incomplete, outdated, or inaccurate. Road conditions,
            traffic, business hours, prices, and weather change — verify locally and exercise your
            own judgment. Tarana.ai is not liable for decisions you make based on generated
            content.
          </p>
        </Section>

        <Section heading="Intellectual property">
          <p>
            The Tarana.ai brand, design, and code are owned by us or our licensors. Your generated
            itineraries are yours to use for personal travel planning. You grant us a limited
            license to store and process your inputs and saved content as needed to operate and
            improve the service. Place photos and data from our place details provider, photo
            providers, and mapping and traffic data provider remain subject to their respective
            licenses.
          </p>
        </Section>

        <Section heading="Third-party services">
          <p>
            The service integrates third parties including our AI itinerary provider, place
            details provider, single sign-on provider, mapping and traffic data provider, weather
            data provider, photo providers, and cloud database and hosting provider. Their
            availability, accuracy, and terms
            are outside our control; your use of their content through Tarana.ai is subject to
            their applicable terms.
          </p>
        </Section>

        <Section heading="Limitation of liability">
          <p>
            To the maximum extent permitted by law, Tarana.ai is provided &ldquo;as is&rdquo;
            without warranties of any kind. We are not liable for indirect, incidental, or
            consequential damages, travel costs, or losses arising from your use of generated
            itineraries, routes, traffic, or weather information.
          </p>
        </Section>

        <Section heading="Termination">
          <p>
            We may suspend or terminate accounts that violate these terms, abuse credits or
            referrals, or threaten the security of the service. You may stop using Tarana.ai at any
            time. On termination, your right to use the service ends; provisions on intellectual
            property, disclaimers, and liability survive.
          </p>
        </Section>

        <Section heading="Changes">
          <p>
            We may update these terms as the service evolves. Material changes will be reflected by
            updating the &ldquo;Last updated&rdquo; date above, and continued use after changes
            means you accept the revised terms.
          </p>
        </Section>

        <Section heading="Contact">
          <p>
            Questions about these terms? Contact us through the app or via the support channels
            listed on our home page. See also our{" "}
            <Link href="/privacy" className="font-medium text-blue-600 hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </Section>

        <div className="mt-12 border-t border-gray-200 pt-6">
          <Link href="/" className="text-sm font-medium text-blue-600 hover:underline">
            ← Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
